name: Publish Docker
on:
  push:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Test Docker Build
      if: github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')
      run: |
        docker build -f ./Dockerfile .
    - name: Publish to Docker Registry
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pyar6329/jupyterlab
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
    - name: Publish to GitHub Package Registry
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/pyar6329/docker-jupyterlab/jupyterlab
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ github.token }}
        tag_semver: true
